export type Brands = {
  id: number;
  en: string;
  ja: string;
  url?: string;
};

const brandlist: Brands[] = [
  { id: 1, en: 'agnes b.', ja: 'アニエスベー', url: 'https://www.agnesb.co.jp/top/CSfTop.jsp' },
  { id: 2, en: 'agnes b. FEMME', ja: 'アニエスベー ファム' },
  { id: 3, en: 'agnes b. HOMME', ja: 'アニエスベー オム' },
  { id: 4, en: 'agnes b. ENFANT', ja: 'アニエスベー アンファン' },
  { id: 5, en: 'agnes b. LAYETTE', ja: 'アニエスベー レイエット' },
  { id: 6, en: 'agnes b. VOYAGE', ja: 'アニエスベー ボヤージュ' },
  { id: 7, en: 'agnes b. SELECTIVE', ja: 'アニエスベー セレクティブ' },
  { id: 8, en: 'Apple', ja: 'アップル', url: 'https://www.apple.com/jp/' },
  { id: 9, en: 'A.P.C', ja: 'アーぺーセー', url: 'https://www.apcjp.com/jpn/' },
  { id: 10, en: "ARC'TERYX", ja: 'アークテリクス', url: 'https://arcteryx.jp/' },
  {
    id: 11,
    en: 'ALAIA (Azzedine Alaia)',
    ja: 'アライア (アズディン アライア)',
    url: 'https://www.maison-alaia.com/jp',
  },
  { id: 12, en: 'Alexander McQUEEN', ja: 'アレキサンダー マックイーン', url: 'https://www.alexandermcqueen.com/ja-jp' },
  {
    id: 13,
    en: 'AMI Alexandre Mattiussi',
    ja: 'アミ アレキサンドル マテティッシュ',
    url: 'https://www.amiparis.com/ja-jp',
  },
  { id: 14, en: 'Anya Hindmarch', ja: 'アニヤ ハインドマーチ', url: 'https://www.anyahindmarch.jp/' },
  { id: 15, en: 'Audemars Piguet', ja: 'オーデマ ピゲ', url: 'https://www.audemarspiguet.com/com/ja/' },
  { id: 16, en: 'BUCCELLATI', ja: 'ブチェラッティ', url: 'https://www.buccellati.com/jp_jp/' },
  { id: 18, en: 'drew house', ja: 'ドリュー ハウス', url: 'https://thehouseofdrew.com/' },
  { id: 20, en: 'Dyson', ja: 'ダイソン', url: 'https://www.dyson.co.jp/ja' },
  { id: 21, en: 'ecco', ja: 'エコー', url: 'https://jp.ecco.com/' },
  { id: 22, en: 'FEAR OF GOD', ja: 'フィアオブゴッド', url: 'https://fearofgod.com/en-jp/collections/fearofgod' },
  { id: 24, en: 'JIL SANDER', ja: 'ジル サンダー', url: 'https://www.jilsander.com/ja-jp/' },
  { id: 25, en: 'JILL STUART', ja: 'ジル スチュアート (ブランド終了)' },
  { id: 27, en: 'HOKA ONE ONE', ja: 'ホカ オネオネ', url: 'https://www.hoka.com/jp/' },
  { id: 28, en: 'HUMAN MADE', ja: 'ヒューマンメイド', url: 'https://humanmade.jp/' },
  { id: 29, en: 'KLASSE14', ja: 'クラス14', url: 'https://klasse14.co.jp/' },
  { id: 30, en: 'KENZO', ja: 'ケンゾー', url: 'https://www.kenzo.com/ja-jp/home' },
  { id: 31, en: 'Le Creuset', ja: 'ル・クルーゼ', url: 'https://www.lecreuset.co.jp/' },
  { id: 32, en: 'Le Coq Sportif', ja: 'ルコックスポルティフ', url: 'https://store.descente.co.jp/lecoqsportif/' },
  { id: 34, en: 'Maison Margiela', ja: 'メゾン マルジェラ', url: 'https://www.maisonmargiela.com/ja-jp/' },
  {
    id: 35,
    en: 'MM6 Maison Margiela',
    ja: 'エムエム6 メゾン マルジェラ',
    url: 'https://www.maisonmargiela.com/ja-jp/mm6/',
  },
  { id: 36, en: 'MANOLO BLAHNIK', ja: 'マノロ ブラニク', url: 'https://strasburgo.co.jp/brand/manoloblahnik-w/' },
  { id: 37, en: 'MARNI', ja: 'マルニ', url: 'https://www.marni.com/ja-jp/' },
  { id: 38, en: 'NIXON', ja: 'ニクソン (国内取扱終了)' },
  { id: 39, en: 'off white', ja: 'オフホワイト', url: 'https://www.off---white.com/en-jp' },
  { id: 40, en: 'OOFOS', ja: 'ウーフォス', url: 'https://oofos.jp/' },
  { id: 41, en: 'POLA', ja: 'ポーラ' },
  { id: 43, en: 'RALPH LAUREN', ja: 'ラルフローレン', url: 'https://www.ralphlauren.co.jp/' },
  { id: 44, en: 'Reebok', ja: 'リーボック' },
  { id: 45, en: 'RIMOWA', ja: 'リモワ', url: 'https://www.rimowa.com/jp/ja/home' },
  { id: 46, en: 'Ron Herman', ja: 'ロンハーマン', url: 'https://ronherman.jp/' },
  { id: 47, en: 'Rick Owens', ja: 'リック オウエンス', url: 'https://www.rickowens.eu/en/JP' },
  { id: 48, en: 'SKAGEN', ja: 'スカーゲン', url: 'https://www.skagen.com/ja-jp/' },
  { id: 51, en: 'Stone Island', ja: 'ストーンアイランド', url: 'https://www.stoneisland.com/ja-jp/' },
  { id: 53, en: 'SK-Ⅱ', ja: 'エスケーツー' },
  { id: 54, en: 'Swatch', ja: 'スウォッチ', url: 'https://www.swatch.com/ja-jp/' },
  { id: 55, en: 'TEVA', ja: 'テヴァ', url: 'https://jp.teva.com/' },
  { id: 57, en: 'Yohji Yamamoto', ja: 'ヨウジヤマモト', url: 'https://www.yohjiyamamoto.co.jp/' },
  { id: 58, en: 'Yohji Yamamoto ( Y-3 )', ja: 'ワイスリー' },
  { id: 59, en: "Yohji Yamamoto ( S'YTE )", ja: 'サイト' },
  { id: 60, en: 'Yohji Yamamoto ( Ground Y )', ja: 'グラウンド ワイ' },
  { id: 61, en: "Yohji Yamamoto ( Y's )", ja: 'ワイズ' },
  { id: 62, en: "Yohji Yamamoto ( Y's.... )", ja: 'ワイズ....' },
  { id: 63, en: "Yohji Yamamoto ( Y's for men )", ja: 'ワイズフォーメン' },
  { id: 64, en: 'Yohji Yamamoto ( power of the WHITE shirt )', ja: 'パワー オブ ザ ホワイトシャツ' },
  { id: 65, en: 'Yohji Yamamoto ( LIMI feu )', ja: 'リミ フゥ' },
  { id: 66, en: 'Beats by Dr. Dre', ja: 'ビーツ バイ ドクタードレー', url: 'https://www.beatsbydre.com/jp' },
  { id: 69, en: 'MOSCHINO', ja: 'モスキーノ', url: 'https://www.moschino.com/jp_ja' },
  { id: 71, en: 'THOM BROWNE', ja: 'トム ブラウン', url: 'https://www.thombrowne.com/ja-jp' },
  {
    id: 72,
    en: 'BEAUTY&YOUTH UNITED ARROWS',
    ja: 'ビューティーアンドユース ユナイテッドアローズ',
    url: 'https://store.united-arrows.co.jp/brand/by/',
  },
  { id: 73, en: 'Manhattan Portage', ja: 'マンハッタンポーテージ', url: 'https://www.manhattanportage.co.jp/' },
  { id: 74, en: 'NINE WEST', ja: 'ナインウエスト', url: 'https://ninewest.com/' },
  { id: 75, en: 'SALOMON', ja: 'サロモン', url: 'https://salomon.jp/' },
  { id: 76, en: "TOD'S", ja: 'トッズ', url: 'https://www.tods.com/jp-ja/home/' },
  { id: 78, en: 'BOSE', ja: 'ボーズ', url: 'https://www.bose.co.jp/ja_jp/' },
  { id: 79, en: 'JBL', ja: 'ジェイビーエル', url: 'https://jp.jbl.com/' },
  { id: 81, en: 'SERAPIAN', ja: 'セラピアン', url: 'https://www.serapian.com/ja-jp' },
  { id: 82, en: 'TOM FORD', ja: 'トムフォード', url: 'https://www.tomford.com/' },
  { id: 83, en: 'BOY LONDON', ja: 'ボーイロンドン', url: 'https://boy-london-jp.com/' },
  { id: 85, en: 'marimekko', ja: 'マリメッコ', url: 'https://www.marimekko.jp/' },
  { id: 86, en: 'Sergio rossi', ja: 'セルジオロッシ', url: 'https://www.sergiorossi.com/jp-ja/' },
  { id: 87, en: 'TOMMY HILFIGER', ja: 'トミー・ヒルフィガー', url: 'https://japan.tommy.com/' },
  { id: 88, en: 'AMI Alexandre Mattiussi ( AMI Paris )', ja: 'アミ アレクサンドル マテュッシ (アミ パリス)' },
  { id: 89, en: 'BREE', ja: 'ブリー ( サイトダウン中 )' },
  { id: 90, en: 'FILA', ja: 'フィラ', url: 'https://www.fila.jp/top/CSfTop.jsp' },
  { id: 94, en: 'TOPKAPI', ja: 'トプカピ', url: 'https://cricket-web.co.jp/pages/topkapi' },
  { id: 95, en: 'ANYA HINDMARCH', ja: 'アニャ・ハインドマーチ', url: 'https://www.anyahindmarch.jp/' },
  { id: 97, en: 'FitFlop', ja: 'フィットフロップ', url: 'https://www.fitflop.jp/' },
  { id: 98, en: 'Marshall', ja: 'マーシャル', url: 'https://www.marshall.com/jp/en' },
  { id: 99, en: 'POLENE', ja: 'ポレーヌ', url: 'https://jp.polene-paris.com/' },
  { id: 100, en: 'SKINS', ja: 'スキン', url: 'https://www.grip-inter.com/shop/c/cSK/' },
  { id: 101, en: 'UNDER ARMOUR', ja: 'アンダーアーマー', url: 'https://www.underarmour.co.jp/top/CSfTop.jsp' },
  { id: 102, en: 'Carhartt', ja: 'カーハート', url: 'https://carhartt-wip.jp/' },
  { id: 103, en: 'FRANKLIN & MARSHALL', ja: 'フランクリンマーシャル', url: 'https://www.franklinandmarshall.com/' },
  { id: 105, en: 'Max&Co.', ja: 'マックスアンドコー', url: 'https://jp.maxandco.com/' },
  { id: 106, en: 'Quiksilver', ja: 'クイックシルバー', url: 'https://boardriders.co.jp/pages/quiksilver' },
  { id: 107, en: 'Staub', ja: 'ストウブ', url: 'https://www.zwilling.com/jp/staub/' },
  { id: 108, en: 'UNITED ARROWS', ja: 'ユナイテッドアローズ', url: 'https://store.united-arrows.co.jp/brand/ua/' },
  { id: 109, en: 'Disney', ja: 'ディズニー' },
  {
    id: 110,
    en: 'green label relaxing',
    ja: 'グリーンレーベルリラクシング',
    url: 'https://store.united-arrows.co.jp/brand/glr/',
  },
  { id: 111, en: 'Mezaik', ja: 'メザイク', url: 'https://www.artsbrains.co.jp/' },
  { id: 112, en: 'Reebok', ja: 'リーボック' },
  { id: 114, en: 'VASIC', ja: 'ヴァジック', url: 'https://www.vasic-newyork.jp/' },
  { id: 116, en: 'Dr.Martens', ja: 'ドクターマーチン', url: 'https://jp.drmartens.com/' },
  { id: 117, en: 'GREGORY', ja: 'グレゴリー', url: 'https://www.gregory.jp/' },
  { id: 119, en: 'MICHAEL KORS', ja: 'マイケルコース', url: 'https://www.michaelkors.jp/' },
  { id: 121, en: 'BEAMS', ja: 'ビームス', url: 'https://www.beams.co.jp/' },
  { id: 122, en: 'DRESSCAMP', ja: 'ドレスキャンプ', url: 'http://www.dresscamp.org/' },
  { id: 123, en: 'Herve Chapelier', ja: 'エルベシャプリエ', url: 'https://hervechapelierjapon.com/' },
  { id: 124, en: 'MAISON KITSUNE', ja: 'メゾン キツネ', url: 'https://maisonkitsune.com/jp/' },
  { id: 125, en: 'milaschon', ja: 'ミラショーン', url: 'https://www.coronet-store.jp/view/page/milaschon' },
  { id: 127, en: 'YONEX', ja: 'ヨネックス', url: 'https://www.yonex.co.jp/' },
];

// 昇順に並び替え
brandlist.sort((a: Brands, b: Brands): number => a.en.localeCompare(b.en));

// 重複削除
const unique = new Map<string, Brands>();
brandlist.forEach((brand: Brands): void => {
  unique.set(brand.en.toLowerCase(), brand);
});

const uniqueBrandlist: Brands[] = Array.from(unique.values());

export default uniqueBrandlist;
